<template>
    <div>
        <div>
      <b-carousel
        id="carousel-fade"
        style="text-shadow: 0px 0px 2px #000"
        fade
        indicators
        img-width="1024"
        img-height="50"
      >
        <b-carousel-slide
          img-src="https://picsum.photos/1024/50/?image=10"
        ></b-carousel-slide>
        <b-carousel-slide
          img-src="https://picsum.photos/1024/50/?image=12"
        ></b-carousel-slide>
        <b-carousel-slide
          img-src="https://picsum.photos/1024/50/?image=22"
        ></b-carousel-slide>
      </b-carousel>
    </div>
    </div>
</template>
